[[headers]]
  for = "/resources/:id/template.rb"
  [headers.values]
    Content-Type = "application/x-thor-template; charset=utf-8"
    Access-Control-Allow-Origin = "*"
    Cache-Control = "no-cache"

[build]
  command = "bin/rails perron:build"

  publish = "output"

  [build.environment]
    RAILS_ENV = "production"

    RUBY_VERSION = "3.4.5"
